# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# An attractive theme
ZSH_THEME="robbyrussell"

# hyphen insensitive
HYPHEN_INSENSITIVE="true"

# disable marking untracked files under VCS as dirty. This makes repository status 
# check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# list of plugins
plugins=(git)

# User configuration
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

#set vim as the editor
EDITOR=vim
export EDITOR

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Aliases
alias cls="clear"
alias extract="tar -xzvf"

export TERM='xterm-256color'

# this takes care of ssh and pgp management
eval $(keychain --quiet --agents gpg,ssh --eval id_rsa github_id_rsa FD0E9B93)

source ~/.zsh_local
